// <auto-generated />
namespace PersonalVideoGameLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class videogamepic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(videogamepic));
        
        string IMigrationMetadata.Id
        {
            get { return "202106230203309_videogamepic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
